name: 'AutoCodeRover Action'
description: 'Run AutoCodeRover for automatic program repair'
inputs:
  bug_id:
    description: 'Bug ID to repair'
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    
    - name: Install AutoCodeRover
      run: |
        echo "::group::Installing AutoCodeRover..."
        python -m pip install --upgrade pip
        pip install auto-code-rover
        echo "::endgroup::"
      shell: bash

    - name: Run AutoCodeRover
      env:
        BUG_ID: ${{ inputs.bug_id }}
      run: auto-code-rover repair --bug-id "$BUG_ID"
      shell: bash

    - name: Summarize Repair Results
      if: always()
      run: |
        if [ -d "repair_results" ]; then
          echo "## ðŸ› ï¸ AutoCodeRover Repair Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Repair attempts completed. Below are the generated artifacts:" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          ls -R repair_results/ >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
        else
          echo "## âš ï¸ No Results Found" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "The repair process did not generate a 'repair_results' directory." >> $GITHUB_STEP_SUMMARY
        fi
      shell: bash
