name: 'AutoCodeRover Action'
description: 'Run AutoCodeRover for automatic program repair'
inputs:
  bug_id:
    description: 'Bug ID to repair'
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Clone AutoCodeRover
      uses: actions/checkout@v4
      with:
        repository: AutoCodeRoverSG/auto-code-rover
        ref: 585d3e639aeda58ef0b6a151dd1cc2721a94d267
        path: auto-code-rover

    - name: Cache Pip Dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('auto-code-rover/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r auto-code-rover/requirements.txt
      shell: bash

    - name: Run AutoCodeRover
      run: |
        export PYTHONPATH=$PYTHONPATH:$(pwd)/auto-code-rover
        python auto-code-rover/app/main.py repair --bug-id "$BUG_ID"
      env:
        BUG_ID: ${{ inputs.bug_id }}
      shell: bash

    - name: List repair results
      run: ls -R repair_results/
      shell: bash
