name: 'AutoCodeRover Action'
description: 'Run AutoCodeRover for automatic program repair'
inputs:
  bug_id:
    description: 'Bug ID to repair'
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up Python
      # Optimization: Upgrade to setup-python@v5 (Node 20 runtime) for better performance and security
      uses: actions/setup-python@v5
      with:
        # Optimization: Upgrade to Python 3.12 for significant runtime performance improvements
        # Note: Validated against upstream environment.yml which specifies python=3.12.5
        python-version: '3.12'
    
    - name: Install AutoCodeRover
      run: |
        python -m pip install --upgrade pip
        pip install auto-code-rover
      shell: bash

    - name: Run AutoCodeRover
      run: auto-code-rover repair --bug-id ${{ inputs.bug_id }}
      shell: bash

    - name: List repair results
      run: ls -R repair_results/
      shell: bash