name: 'AutoCodeRover Action'
description: 'Run AutoCodeRover for automatic program repair'
inputs:
  bug_id:
    description: 'Bug ID to repair'
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    
    - name: Install AutoCodeRover
      run: |
        echo "::group::📦 Installing AutoCodeRover Dependencies..."
        python -m pip install --upgrade pip
        pip install auto-code-rover
        echo "::endgroup::"
        echo "✅ Dependencies installed."
      shell: bash

    - name: Run AutoCodeRover
      run: |
        echo "🚀 Starting AutoCodeRover repair for Bug ID: ${{ inputs.bug_id }}"
        auto-code-rover repair --bug-id ${{ inputs.bug_id }}
      shell: bash

    - name: List repair results
      run: |
        echo "### 🛠️ Repair Results" >> $GITHUB_STEP_SUMMARY
        if [ -d "repair_results" ]; then
          echo "The following results were generated:" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          ls -R repair_results/ >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          echo "✅ Repair results found."
        else
          echo "⚠️ No results directory found." >> $GITHUB_STEP_SUMMARY
          echo "⚠️ No results directory found."
        fi
      shell: bash