name: 'AutoCodeRover Action'
description: 'Run AutoCodeRover for automatic program repair'
inputs:
  bug_id:
    description: 'Bug ID to repair'
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'

    - name: Get pip cache dir
      id: pip-cache
      run: |
        echo "dir=$(pip cache dir)" >> $GITHUB_OUTPUT
      shell: bash

    - name: Cache pip
      uses: actions/cache@v3
      with:
        path: ${{ steps.pip-cache.outputs.dir }}
        key: ${{ runner.os }}-pip-${{ github.run_id }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install AutoCodeRover
      run: |
        echo "::group::Install AutoCodeRover"
        python -m pip install --upgrade pip
        pip install auto-code-rover
        echo "::endgroup::"
      shell: bash

    - name: Run AutoCodeRover
      env:
        BUG_ID: ${{ inputs.bug_id }}
      run: auto-code-rover repair --bug-id "$BUG_ID"
      shell: bash

    - name: List repair results
      run: |
        if [ -d "repair_results" ]; then
           ls -R repair_results/
           {
             echo "## ðŸ› ï¸ Repair Results"
             echo ""
             echo "The following results were generated:"
             echo '```'
             ls -R repair_results/
             echo '```'
           } >> "$GITHUB_STEP_SUMMARY"
        else
           echo "::error::repair_results directory not found"
           echo "âš ï¸ No results directory found." >> "$GITHUB_STEP_SUMMARY"
           exit 1
        fi
      shell: bash