name: 'AutoCodeRover Action'
description: 'Run AutoCodeRover for automatic program repair'
inputs:
  bug_id:
    description: 'Bug ID (GitHub Issue ID) to repair'
    required: true
  openai_key:
    description: 'OpenAI API Key'
    required: true
  model:
    description: 'Model to use (e.g. gpt-4o-2024-05-13)'
    default: 'gpt-4o-2024-05-13'
    required: false
runs:
  using: "composite"
  steps:
    - name: 🎨 Pre-flight UX Check
      run: |
        if [ -z "${{ inputs.openai_key }}" ]; then
          echo "::error::🎨 Palette: Oops! You forgot the OpenAI Key. I need it to see the code!"
          exit 1
        fi
        echo "🎨 Palette: All systems go! Preparing to paint some code fixes..."
      shell: bash

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install AutoCodeRover
      run: |
        echo "::group::🎨 Palette: Setting up AutoCodeRover..."

        ACR_DIR="${{ runner.temp }}/auto-code-rover"

        # Clone AutoCodeRover and pin to a specific commit for stability
        echo "Cloning AutoCodeRover to $ACR_DIR..."
        git clone https://github.com/AutoCodeRoverSG/auto-code-rover.git "$ACR_DIR"
        cd "$ACR_DIR"
        git checkout 585d3e639aeda58ef0b6a151dd1cc2721a94d267

        echo "Installing dependencies..."
        python -m pip install --upgrade pip
        pip install -r requirements.txt

        echo "ACR_DIR=$ACR_DIR" >> $GITHUB_ENV

        echo "::endgroup::"
        echo "✅ AutoCodeRover installed successfully!"
      shell: bash

    - name: Run AutoCodeRover
      run: |
        echo "::group::🎨 Palette: Running AutoCodeRover on Issue #${{ inputs.bug_id }}..."

        export OPENAI_KEY="${{ inputs.openai_key }}"
        export PYTHONPATH="$ACR_DIR"

        cd "$ACR_DIR"

        # Run AutoCodeRover in 'github-issue' mode
        python app/main.py github-issue \
          --output-dir ${{ github.workspace }}/repair_results \
          --setup-dir ${{ github.workspace }}/acr_setup \
          --model "${{ inputs.model }}" \
          --task-id "${{ inputs.bug_id }}" \
          --clone-link "https://github.com/${{ github.repository }}.git" \
          --commit-hash "${{ github.sha }}" \
          --issue-link "https://github.com/${{ github.repository }}/issues/${{ inputs.bug_id }}"

        echo "::endgroup::"
      shell: bash

    - name: List repair results
      if: always()
      run: |
        if [ -d "repair_results" ]; then
          echo "::group::🎨 Palette: Repair Results"
          ls -R repair_results/
          echo "::endgroup::"
        else
          echo "::warning::🎨 Palette: No repair results found."
        fi
      shell: bash
