name: 'AutoCodeRover Action'
description: 'Run AutoCodeRover for automatic program repair'
inputs:
  bug_id:
    description: 'Bug ID to repair'
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Cache Pip
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/pip
          ~/Library/Caches/pip
        key: ${{ runner.os }}-pip-${{ github.run_id }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install AutoCodeRover
      run: |
        echo "::group::Install AutoCodeRover"
        python -m pip install --upgrade pip
        pip install auto-code-rover
        echo "::endgroup::"
      shell: bash

    - name: Run AutoCodeRover
      run: auto-code-rover repair --bug-id ${{ inputs.bug_id }}
      shell: bash

    - name: List repair results
      run: |
        if [ -d "repair_results/" ]; then
          ls -R repair_results/
        else
          echo "repair_results/ directory not found."
        fi
      shell: bash
