name: 'AutoCodeRover Action'
description: 'Run AutoCodeRover for automatic program repair'
inputs:
  bug_id:
    description: 'Bug ID to repair'
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    
    - name: Install AutoCodeRover
      run: |
        echo "::group::Install AutoCodeRover"
        python -m pip install --upgrade pip
        pip install auto-code-rover
        echo "::endgroup::"
      shell: bash

    - name: Run AutoCodeRover
      env:
        BUG_ID: ${{ inputs.bug_id }}
      run: |
        echo "🚀 Starting AutoCodeRover for Bug ID: $BUG_ID"
        auto-code-rover repair --bug-id "$BUG_ID"
      shell: bash

    - name: List repair results
      run: |
        if [ -d "repair_results" ]; then
           ls -R repair_results/
           {
             echo "## 🛠️ Repair Results"
             echo ""

             patches=$(find repair_results -name "*.patch" -o -name "*.diff")
             if [ -n "$patches" ]; then
                echo "### ✨ Generated Patches"
                for patch in $patches; do
                  echo "<details>"
                  echo "<summary>Preview: $(basename "$patch")</summary>"
                  echo ""
                  echo "\`\`\`diff"
                  cat "$patch"
                  echo "\`\`\`"
                  echo ""
                  echo "</details>"
                  echo ""
                done
             fi

             echo "### 📂 Output Files"
             echo '```'
             ls -R repair_results/
             echo '```'
           } >> "$GITHUB_STEP_SUMMARY"
        else
           echo "::error::repair_results directory not found"
           echo "⚠️ No results directory found." >> "$GITHUB_STEP_SUMMARY"
           exit 1
        fi
      shell: bash