name: 'AutoCodeRover Action'
description: 'Run AutoCodeRover for automatic program repair'
inputs:
  bug_id:
    description: 'Bug ID to repair'
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    
    - name: Install AutoCodeRover
      run: |
        echo "::group::Installing AutoCodeRover..."
        python -m pip install --upgrade pip
        pip install auto-code-rover
        echo "::endgroup::"
      shell: bash

    - name: Run AutoCodeRover
      run: auto-code-rover repair --bug-id ${{ inputs.bug_id }}
      shell: bash

    - name: List repair results
      run: |
        if [ -d "repair_results" ]; then
          echo "::notice::Repair results found!"
          ls -R repair_results/
        else
          echo "::warning::No repair_results directory found. AutoCodeRover might have failed to generate a fix."
        fi
      shell: bash